const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || ""Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVBqdWZrT3YrekFWTm1tYkx3TFBzOUZMbm03R1N2c2pPSWVIQnpRc0RVND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUIxVkpONWM2TXlqbjFyRHJLN0JUbG5YdVFYTkN3ZlVvU215b0tuTlpGQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjQlRGMFVJK1YrN3ZPYTJwci8yT3c5SkdVTk5Ebmh0YnFpT3JTTG5aVVdzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJwZFYvNkQxTCtuWXJ1ZWFqekdBOVZOdk1SME5VMkJrckZCMVlDdktZeng4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFGQTJYejBlRFhyVStibnJ0MW8xVFpXLzBRZUszQlFuTkFjdDI5eHhMM1E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdJaSsyZEdFNEhkRUNQOTB6clFTY2lveW1KNUtNZmFOeUd1MHNZVkxrVXc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0RxbXA4WHBoa0dBcXdtY0FRcXFBdkhQZmRXQXdEczY4VXRFeUJvU2ltWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYlp2OTdvUEdWQjd6eWxKOU4yMUE1ZTQ0cjR4bHdJMEExNjRVWFJaWWdTST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZCRXJ4WldOU2RCT01nby8yOWNGZitlckgzR1VnRXFidmo3aHEveE5Da3ZQYlZPT3N6VEwvOVRXTVV4WWVZYk9ySVg2V3RSc2V4bHByUy9reVQyNENnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTkzLCJhZHZTZWNyZXRLZXkiOiJUNHBhRlJSR1AwZTlyV25ZUkxyaHJBVEprWjRnU1ViNEY0VlJ2U3lxMnlrPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDkwMzg5MDk2MThAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMjAwQURDNThCNDZBQzZBNkE4RjJBNEM4Rjc5QzcyMEIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTk0NTc3N30seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0OTAzODkwOTYxOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI2RDE0RTY3QzZBNDBCNDg4MUY0NUM0ODU4NDBDQzVBMiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1OTQ1Nzc3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzQ5MDM4OTA5NjE4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjBCNEEzMjVCNUFCRUI3QjU1NDQyMDVFQkI5OTA2Q0UzIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzU5NDU3Nzh9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIzNDkwMzg5MDk2MThAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiODMyRTI5N0RDQzc5QkY1NkJCMTIwREI5REEwQjlDQ0YifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTk0NTc3OH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiSTlVekxBTTRST0c0dDdValdkZ1VDZyIsInBob25lSWQiOiI5OWU0NjNhZC04OWUxLTRjYzQtOWFmMC1hMDcwM2Y3MTI5NmEiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiREpSVFVBTHl5S3pUM3hJYnpoUTBhRDk4RklRPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitLbEtqQU13bHA0WTdyd2M3QTZkS214V3dSaz0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJYMlNQTVhCSyIsIm1lIjp7ImlkIjoiMjM0OTAzODkwOTYxODozQHMud2hhdHNhcHAubmV0IiwibmFtZSI6Inhlcm9mZng3MSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTTYvNHNBRkVKL2M0YnNHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiZld4WlQ1V1JKM0pkZU9TRkNrNWdGVWVscXFySFlsVHVkWFBneEsvbTdrRT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiQStIN2lJSk9EY2pWOUJJUzFBcDJQY0xwTWsydW5BTUpERU44QTRmZENYQUUxbENKUzFDZnFaU2hTdm94bGFsdDJsaVhvVU9vZ2RneXFWY2J1UmZ5Q0E9PSIsImRldmljZVNpZ25hdHVyZSI6IkYvbDNicENGYjBGOGdmVW9BRDZlZWFFK3pkRzA3V1p2NVZRS1oxei9LS2JYaSt0RW9USFNtem9neXZVclJhcWpUK2liamRSZzh0MCt1RTBRbVZUMkJ3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0OTAzODkwOTYxODozQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlgxc1dVK1ZrU2R5WFhqa2hRcE9ZQlZIcGFxcXgySlU3blZ6NE1TdjV1NUIifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU5NDU3NzMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBT2VMIn0=
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "2349038909618",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
